- name: check if a directory exists or not, if it does not exist create it.
  hosts: localhost
  vars:
  - name: /app
  tasks:
  - name: check if the directory exists or not
    ansible.builtin.command: cd {{name}}
    register: output
    ignore_errors: true
  - name: check the exit status 
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: craete the directory if not exist
    become: yes
    ansible.builtin.file:
      path: /home/centos/ansible/{{name}} 
      state: directory 
    when: output.rc !=0  

